package org.example.presentation.view;

public enum Actions {
    SHOW_SUBJECT_ALL_LESSONS,
    SHOW_SUBJECT_REMAINING_LESSONS,
    SHOW_SUBJECT_ALL_SUBGROUP_LESSONS,
    SHOW_SUBJECT_REMAINING_SUBGROUP_LESSONS,

    SHOW_TODAY_SCHEDULE,
    SHOW_CURRENT_WEEK_SCHEDULE,
    SHOW_DAY_SCHEDULE,
    SHOW_WEEK_SCHEDULE,

    CREATE_SUBJECT_ALL_LESSONS,
    CREATE_SUBJECT_REMAINING_LESSONS,
    CREATE_ALL_SUBJECTS_ALL_LESSONS,
    CREATE_ALL_SUBJECTS_REMAINING_LESSONS,
}